import Navbar from "@/components/Shared/Navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Shared/Footer/Footer";
import AuthProvider from "@/Provider/AuthProvider/AuthProvider";
import GlobalState from "@/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <GlobalState>
            <Navbar />
            {children}
            <Footer />
          </GlobalState>
        </AuthProvider>
      </body>
    </html>
  );
}
